### ISSUE TITLE
No result output after running QIF 

### ISSUE THREAD

**Issue by Librajiayou** [s3team/Abacus#1]
Hello, I followed your tool's usage doc and ran some examples written by me, but I met some problems and did not have result outputed by QIF.  
Here are problems I met during running Abacus tools： 
1. I tested a machine learning algorithm named dA and set training data(an array of 240 bytes) as secret, but QIF could not output result as expected and showed "killed" during parsing 65% (figure 1), What's wrong if display "killed" during QIF parsing?
2. Can Abacus detect implicit data flow. like branch condition is dependent by value of a variable controlled by secret (figure 2)? In my tested example, it seems not solve such data flow. Thanks!
![2](https://user-images.githubusercontent.com/23275942/111279647-de12c600-8675-11eb-872f-1200397fc896.png)
![3](https://user-images.githubusercontent.com/23275942/111279553-c3405180-8675-11eb-91e8-75bb9cbb8ea1.png)

**Comment by qinkunbao** [comment]
1. Could you please share the input file`Inst_data.txt` and `Function.txt`? 
2. Abacus will not identify the if condition in your example as a secret-dependent control flow in the example. Abacus will report the leakage at line `b = array[secret[1]+2]`.  Here is the reason. `b = array[secret[1]+2]` is a secret data access and is the root cause of the leakage in your example. If a developer fixes the vulnerability at line `b = array[secret[1]+2]`, then the if branch condition won't leak any information.

**Comment by Librajiayou** [comment]
Thanks a lot! I think the input file Inst_data.txt is too big ( with 1.3G ) to upload here, and I upload my example named dA. It's an example downloaded from github and I added an annotation "abacus_make_symbolic()" for using abacus tool.

[Function.txt](https://github.com/s3team/Abacus/files/6153148/Function.txt)
[dA.h.txt](https://github.com/s3team/Abacus/files/6153157/dA.h.txt)
[dA.txt](https://github.com/s3team/Abacus/files/6153158/dA.txt)
[utils.h.txt](https://github.com/s3team/Abacus/files/6153159/utils.h.txt)

(For limited file type can be upload here, I change all file type as txt) Thanks!

**Comment by qinkunbao** [comment]
Hi, 

I was having trouble building the binary executable from the source code you provided. Could you please 
pack the source code (with the makefile if possible) into one archive file (e.g., .gz)? Thanks!

**Comment by Librajiayou** [comment]
I packed all files include makefile into source.tar.gz and hope the code will be running well. Thanks!
[source.tar.gz](https://github.com/s3team/Abacus/files/6168080/source.tar.gz)

**Comment by qinkunbao** [comment]
I built the source code into a binary executable (Attachment). It works on my computer. 

On the other hand, I would say that Abacus typically doesn't work well on ML applications. The main reason is that ML applications usually have lots of floating-point calculations and instructions like AVX. Abacus can not handle those instructions. Under the circumstance, Abacus will forcefully concretize those symbolic formulas into concrete values and miss some vulnerabilities. 

[dA.zip](https://github.com/s3team/Abacus/files/6168284/dA.zip)

**Comment by Librajiayou** [comment]
Thank you for your patient explanation!  
So the reason for displaying "killed" when parsing the trace of my example program may be that Abacus can't handle floating-point calculations and instructions like AVX well? It will not happen in cryptographic algorithm, right?

**Comment by qinkunbao** [comment]
> Thank you for your patient explanation!
> So the reason for displaying "killed" when parsing the trace of my example program may be that Abacus can't handle floating-point calculations and instructions like AVX well? It will not happen in cryptographic algorithm, right?

 Displaying "killed" has nothing to do with floating instructions. You can check the binary I built in the attachment. It has many floating instructions. Since I can not reproduce the error, I don't know the reason. I ran into a similar error ("killed") a long time ago. It turned out to be that the program ran out of memory on my MacBook air. I don't have access to your machine and the environment. Sorry, I don't know what's going on.

**Comment by Librajiayou** [comment]
I will check if the error reason is the same as yours or not. Thank you very much!

**Comment by qinkunbao** [comment]
> I will check if the error reason is the same as yours or not. Thank you very much!

Hi, did you find the reason? You can check the log (e.g., dmesg) to find out why the program is killed.

**Comment by Librajiayou** [comment]
Yes , I checked the log and found the reason was the same as yours, which means "out of memory".

**Comment by qinkunbao** [comment]
Thanks
