### ISSUE TITLE
README.md needs to be updated 

### ISSUE THREAD

**Issue by mainarke** [s3team/Abacus#2]
Hi,

Today when I tried to run the code by following `README.md`, the **Collect the trace** step did not work:
```
pin -t Pintools/obj-ia32/MyPinToolLinux.so -- ./examples/a.out 
```

Then I refer to the `readme.pdf`, Sec. IV-C:
<img width="415" alt="image" src="https://user-images.githubusercontent.com/14142781/117099715-79860480-ada4-11eb-83b8-1673425da32e.png">

I ran this code and it worked. 

I think the instructions in `README.md` needs to be updated to avoid misleading others. Thanks.

**Comment by qinkunbao** [comment]
Yes, `README.md` is kind of outdated. Please refer to `readme.pdf` or `icse_artifact_evaluation.txt`. Those two documents are the latest. 

I am quite busy these days. I hope I can revise `README.md` before ICSE 2021. In the meanwhile, feel free to create PRs if you are interested in updating the documents.

**Comment by qinkunbao** [comment]
The readme has been updated. https://github.com/s3team/Abacus/pull/4
